App/config/routes.rb
Rails.application.routes.draw do
  get 'theapp/index'

  resources :questions
  resources :topics
  resources :sub_categories
  resources :categories

  root 'theapp#index'

end

App/app/models/topic.rb
class Topic < ActiveRecord::Base
end

App/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:id, :sc_id, :topic_n)
    end
end

App/app/helpers/topics_helper.rb
module TopicsHelper
end

App/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :sc_id %><br>
    <%= f.text_field :sc_id %>
  </div>
  <div class="field">
    <%= f.label :topic_n %><br>
    <%= f.text_field :topic_n %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

App/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

App/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Sc</th>
      <th>Topic n</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.id %></td>
        <td><%= topic.sc_id %></td>
        <td><%= topic.topic_n %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

App/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

App/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @topic.id %>
</p>

<p>
  <strong>Sc:</strong>
  <%= @topic.sc_id %>
</p>

<p>
  <strong>Topic n:</strong>
  <%= @topic.topic_n %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>