App/config/routes.rb
Rails.application.routes.draw do
  get 'theapp/index'

  resources :questions
  resources :topics
  resources :sub_categories
  resources :categories

  root 'theapp#index'

end

App/app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
end

App/app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:id, :subject, :cat_id)
    end
end

App/app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

App/app/views/sub_categories/_form.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :cat_id %><br>
    <%= f.text_field :cat_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

App/app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

App/app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Subject</th>
      <th>Cat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.id %></td>
        <td><%= sub_category.subject %></td>
        <td><%= sub_category.cat_id %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub category', new_sub_category_path %>

App/app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_path %>

App/app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @sub_category.id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @sub_category.subject %>
</p>

<p>
  <strong>Cat:</strong>
  <%= @sub_category.cat_id %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>