App/config/routes.rb
Rails.application.routes.draw do
  get 'theapp/index'

  resources :questions
  resources :topics
  resources :sub_categories
  resources :categories

  root 'theapp#index'

end

App/app/models/question.rb
class Question < ActiveRecord::Base
end

App/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:id, :answer, :a, :b, :c, :d, :correct_answer, :correct, :category_id, :sub_cat_id)
    end
end

App/app/helpers/questions_helper.rb
module QuestionsHelper
end

App/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="field">
    <%= f.label :a %><br>
    <%= f.text_area :a %>
  </div>
  <div class="field">
    <%= f.label :b %><br>
    <%= f.text_area :b %>
  </div>
  <div class="field">
    <%= f.label :c %><br>
    <%= f.text_area :c %>
  </div>
  <div class="field">
    <%= f.label :d %><br>
    <%= f.text_area :d %>
  </div>
  <div class="field">
    <%= f.label :correct_answer %><br>
    <%= f.text_area :correct_answer %>
  </div>
  <div class="field">
    <%= f.label :correct %><br>
    <%= f.text_field :correct %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :sub_cat_id %><br>
    <%= f.text_field :sub_cat_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

App/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

App/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Answer</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>Correct answer</th>
      <th>Correct</th>
      <th>Category</th>
      <th>Sub cat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.answer %></td>
        <td><%= question.a %></td>
        <td><%= question.b %></td>
        <td><%= question.c %></td>
        <td><%= question.d %></td>
        <td><%= question.correct_answer %></td>
        <td><%= question.correct %></td>
        <td><%= question.category_id %></td>
        <td><%= question.sub_cat_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

App/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

App/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @question.id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>A:</strong>
  <%= @question.a %>
</p>

<p>
  <strong>B:</strong>
  <%= @question.b %>
</p>

<p>
  <strong>C:</strong>
  <%= @question.c %>
</p>

<p>
  <strong>D:</strong>
  <%= @question.d %>
</p>

<p>
  <strong>Correct answer:</strong>
  <%= @question.correct_answer %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @question.correct %>
</p>

<p>
  <strong>Category:</strong>
  <%= @question.category_id %>
</p>

<p>
  <strong>Sub cat:</strong>
  <%= @question.sub_cat_id %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>